[project]
name = "lunad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "matplotlib>=3.11.1",
    "notebook>=7.6.1",
    "numpy>=2.5.1",
    "openai>=2.51.0",
    "opencv-python>=5.0.0.93",
    "pathlib>=1.0.1",
    "pymodi-plus>=0.4.2",
    "python-dotenv>=1.2.2",
    "scipy>=1.18.0",
    "sounddevice>=0.5.5",
    "tensorflow>=2.21.0",
    "torch>=2.13.0",
    "whisper>=1.1.10",
]

[tool.uv]
override-dependencies = [
    "websocket-client>=1.7"
]
